### ISSUE TITLE
Make Gentle preserve line breaks somehow

### ISSUE THREAD

**Issue by dariusk** [FeelTrainCoop/shortcut#44]
At the moment Gentle doesn't preserve line breaks in the transcript. We may need to fork Gentle to get what we need out of this. But for now we have a temporary solution in place while we move ahead with other features: namely, we assume every new sentence is a new paragraph. Not pretty, but functional.

**Comment by cestanton** [comment]
This got done...by magic? But it's definitely doing it now.
