### ISSUE TITLE
Desynchronization of episode header and transcript

### ISSUE THREAD

**Issue by cestanton** [FeelTrainCoop/shortcut#5]
**Steps to reproduce:**
- Go to an episode
- Change the episode number in the URL route to a different episode, the title updates but the transcript does not until you manually reload

**Suggested fix:** 
Maybe force a componentUpdate on Transcript when previous episode.number is not the same as current

**Comment by dariusk** [comment]
The routing system in the open source version of Shortcut is significantly different (and simpler) than the routing system in the original TAL implementation. As a result this bug doesn't occur on this version, closing.
