### ISSUE TITLE
Need a script/docs change for ffmpeg in case of podcast artwork video channel

### ISSUE THREAD

**Issue by dariusk** [FeelTrainCoop/shortcut#89]
From @janfabry:

> One other issue I had during the conversion to HLS: the podcast I was testing on had embedded artwork, which was encoded as a video track
> ffmpeg got confused, and could not split the audio into 10 second chunks
> I used `-map 0:0` to only select the first stream (which was the audio stream), but `-map 0:a` or `-vn` might also work (select all audio streams, or don't select a video stream)

**Comment by Echelon9** [comment]
Adding my +1 to this.
I came across the same documentation bug when attempting to process some sample podcast episodes.
@janfabry fix of adding `-map 0:0` to `ffmpeg` worked on that particular podcast episode, although I'd expect `-map 0:a` may be a more robust fix.

**Comment by dariusk** [comment]
Thanks @Echelon9, I'll test this with as many different image-embedded formats as I can manage to find.
